//! `hi --spec-review` one-shot against the scripted OpenAI-compatible server:
//! the audit verdict drives the exit code and the `review` report object.

use std::path::{Path, PathBuf};
use std::process::Command;

use hi_ai::test_support::{ChatStep, ScriptedOpenAiServer, ScriptedResponse};

fn hi_bin() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_hi"))
}

struct Fixture {
    root: tempfile::TempDir,
}

impl Fixture {
    fn new() -> Self {
        let root = tempfile::tempdir().unwrap();
        let workspace = root.path().join("workspace");
        std::fs::create_dir_all(workspace.join("docs")).unwrap();
        std::fs::create_dir_all(workspace.join("src")).unwrap();
        std::fs::write(
            workspace.join("plan.md"),
            "# Plan\n\n- [x] Welcome banner\n- [ ] KICK command\n- [ ] /topic command\n",
        )
        .unwrap();
        std::fs::write(
            workspace.join("docs/spec.md"),
            "# Spec\n\nThe server greets each client with Welcome.\nKICK removes a user.\n/topic sets the channel topic.\n",
        )
        .unwrap();
        std::fs::write(workspace.join("src/main.rs"), "fn main() {}\n").unwrap();
        for dir in [
            "home",
            "xdg-config",
            "xdg-data",
            "xdg-state",
            "xdg-cache",
            "tmp",
        ] {
            std::fs::create_dir_all(root.path().join(dir)).unwrap();
        }
        std::fs::write(
            root.path().join("xdg-config/hi.toml"),
            "# generated by spec_review_headless test\n[sync]\nmode = \"off\"\n",
        )
        .unwrap();
        Self { root }
    }

    fn workspace(&self) -> PathBuf {
        self.root.path().join("workspace")
    }

    fn report(&self) -> PathBuf {
        self.root.path().join("report.json")
    }

    fn run(&self, server: &ScriptedOpenAiServer, extra: &[&str]) -> std::process::Output {
        let root = self.root.path();
        let mut command = Command::new(hi_bin());
        command
            .current_dir(self.workspace())
            .arg("--spec-review")
            .args(extra)
            .arg("--plain")
            .arg("--no-save")
            .arg("--config")
            .arg(root.join("xdg-config/hi.toml"))
            .arg("--report")
            .arg(self.report())
            .arg("--model")
            .arg("test-model")
            .arg("--base-url")
            .arg(server.v1_url())
            .arg("--api-key")
            .arg("spec-review-test-key")
            .arg("--no-verify")
            .arg("--no-memory")
            .arg("--no-finalize")
            .arg("--no-rsi")
            .arg("--no-tasks")
            .arg("--no-autoharnessfix")
            .arg("--no-auto-compact")
            .arg("--review")
            .arg("off")
            .arg("--lsp")
            .arg("off")
            .env_clear()
            .env("HOME", root.join("home"))
            .env("XDG_CONFIG_HOME", root.join("xdg-config"))
            .env("XDG_DATA_HOME", root.join("xdg-data"))
            .env("XDG_STATE_HOME", root.join("xdg-state"))
            .env("XDG_CACHE_HOME", root.join("xdg-cache"))
            .env("HI_STATE_ROOT", root.join("xdg-state/hi"))
            .env("TMPDIR", root.join("tmp"))
            .env(
                "PATH",
                std::env::var("PATH").unwrap_or_else(|_| "/usr/local/bin:/usr/bin:/bin".into()),
            )
            .env("LANG", "C")
            .env("LC_ALL", "C")
            .env("HI_SKIP_TUTORIAL", "1")
            .env("HI_SUGGEST_NEXT_PROMPT", "0")
            .env("HI_DISABLE_UPDATE_CHECK", "1")
            .env("HI_DISABLE_FEEDBACK", "1")
            .env("HI_TRACE_CAPTURE", "off")
            .env("RUST_BACKTRACE", "1");
        command.output().expect("spawning hi")
    }
}

fn report_json(path: &Path) -> serde_json::Value {
    let raw = std::fs::read_to_string(path)
        .unwrap_or_else(|err| panic!("reading {}: {err}", path.display()));
    serde_json::from_str(&raw).expect("report is JSON")
}

fn describe(output: &std::process::Output) -> String {
    format!(
        "status {:?}\n--- stdout ---\n{}\n--- stderr ---\n{}",
        output.status.code(),
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    )
}

fn scripted(replies: &[&str]) -> Option<ScriptedOpenAiServer> {
    ScriptedOpenAiServer::new(
        replies
            .iter()
            .map(|reply| ChatStep::new(ScriptedResponse::text(reply)))
            .collect(),
    )
}

const CLEAN_VERDICT: &str = "Coverage: everything in plan.md and docs/spec.md is implemented.\n\n\
<review>\n\
verdict: COMPLETE\n\
coverage: implemented | Welcome banner | src/main.rs:1\n\
coverage: implemented | KICK command | src/main.rs:1\n\
coverage: implemented | /topic command | src/main.rs:1\n\
finding: none\n\
residual: none\n\
</review>";

const INCOMPLETE_VERDICT: &str = "Coverage: /topic is not implemented.\n\n\
<review>\n\
verdict: INCOMPLETE\n\
coverage: implemented | Welcome banner | src/main.rs:1\n\
coverage: implemented | KICK command | src/main.rs:1\n\
coverage: missing | /topic command | -\n\
finding: none\n\
residual: /topic is out of scope for a fix pass\n\
</review>";

const P0_VERDICT: &str = "One release blocker.\n\n\
<review>\n\
verdict: INCOMPLETE\n\
coverage: implemented | Welcome banner | src/main.rs:1\n\
coverage: partial | KICK command | src/main.rs:1\n\
coverage: missing | /topic command | -\n\
finding: P0 | Reject empty nicknames | src/main.rs:1\n\
finding: P2 | Log unknown commands | src/missing.rs:3\n\
residual: none\n\
</review>";

#[test]
fn clean_audit_exits_zero_with_review_report() {
    let Some(server) = scripted(&[CLEAN_VERDICT]) else {
        return;
    };
    let fixture = Fixture::new();
    let output = fixture.run(&server, &[]);
    let text = describe(&output);
    assert_eq!(output.status.code(), Some(0), "{text}");
    assert!(
        String::from_utf8_lossy(&output.stdout).contains("spec review complete"),
        "{text}"
    );
    let report = report_json(&fixture.report());
    let review = &report["review"];
    assert_eq!(review["exit_code"], 0, "{review}");
    assert_eq!(review["verdict"], "complete");
    assert_eq!(review["coverage_complete"], true);
    assert_eq!(review["coverage"].as_array().unwrap().len(), 3);
    assert_eq!(review["findings"].as_array().unwrap().len(), 0);
    assert_eq!(review["passes"], 0);
    assert_eq!(review["phase"], "done");
    let files = review["inputs"]["files"].as_array().unwrap();
    assert_eq!(files.len(), 2, "{review}");
    assert_eq!(files[0]["path"], "plan.md");
    assert_eq!(files[1]["path"], "docs/spec.md");
    assert_eq!(report["outcome"]["status"], "completed");
}

#[test]
fn incomplete_coverage_exits_three() {
    let Some(server) = scripted(&[INCOMPLETE_VERDICT]) else {
        return;
    };
    let fixture = Fixture::new();
    let output = fixture.run(&server, &[]);
    let text = describe(&output);
    assert_eq!(output.status.code(), Some(3), "{text}");
    assert!(
        String::from_utf8_lossy(&output.stderr).contains("2/3 plan/spec items implemented"),
        "{text}"
    );
    let review = &report_json(&fixture.report())["review"];
    assert_eq!(review["exit_code"], 3);
    assert_eq!(review["verdict"], "incomplete");
    assert_eq!(review["coverage"][2]["state"], "missing");
    assert_eq!(review["residual"], "/topic is out of scope for a fix pass");
}

#[test]
fn audit_only_with_open_p0_exits_four_and_flags_bad_citations() {
    let Some(server) = scripted(&[P0_VERDICT]) else {
        return;
    };
    let fixture = Fixture::new();
    let output = fixture.run(&server, &["--spec-review-audit-only"]);
    let text = describe(&output);
    assert_eq!(output.status.code(), Some(4), "{text}");
    let review = &report_json(&fixture.report())["review"];
    assert_eq!(review["exit_code"], 4);
    assert_eq!(review["audit_only"], true);
    assert_eq!(review["passes"], 0, "audit-only never starts a fix pass");
    assert_eq!(review["open_blocking"], 1);
    let findings = review["findings"].as_array().unwrap();
    assert_eq!(findings.len(), 2);
    assert_eq!(findings[0]["severity"], "P0");
    assert_eq!(findings[0]["verified"], true);
    assert_eq!(
        findings[1]["verified"], false,
        "src/missing.rs does not exist"
    );
    assert_eq!(
        review["unverified_citations"].as_array().unwrap().len(),
        1,
        "{review}"
    );
}

#[test]
fn missing_verdict_block_reasks_once_then_exits_five() {
    let Some(server) = scripted(&["I looked around; nothing to report.", "Still no block."]) else {
        return;
    };
    let fixture = Fixture::new();
    let output = fixture.run(&server, &[]);
    let text = describe(&output);
    assert_eq!(output.status.code(), Some(5), "{text}");
    let review = &report_json(&fixture.report())["review"];
    assert_eq!(review["exit_code"], 5);
    assert_eq!(review["phase"], "stopped");
    assert!(
        review["stop_reason"]
            .as_str()
            .unwrap()
            .contains("no parseable <review> block"),
        "{review}"
    );
    server
        .assert_clean()
        .expect("both scripted replies consumed");
}

#[test]
fn explicit_missing_input_exits_two_without_a_model_call() {
    let Some(server) = scripted(&[]) else {
        return;
    };
    let fixture = Fixture::new();
    let output = fixture.run(&server, &["docs/nope.md"]);
    let text = describe(&output);
    assert_eq!(output.status.code(), Some(2), "{text}");
    assert!(
        String::from_utf8_lossy(&output.stderr).contains("no such file: docs/nope.md"),
        "{text}"
    );
    assert!(!fixture.report().exists(), "no report without a turn");
}
