#!/usr/bin/env bash
#
# CI line-count gate for the Rust crates.
#
# Fails (exit 1) if any crate source file under crates/**/src/*.rs exceeds the
# line limit below, printing each offender with its line count. Excludes
# generated code (files matching */gen/* or containing a generated-code marker on
# their first few lines). Intended for CI; run locally with:
#
#     scripts/check_file_size.sh
#
# The limit is a forcing function: when a file crosses it, factor rather than
# append. The expected initial offenders (the kept integration cores) are
# hi-agent/src/lib.rs and hi-tui/src/lib.rs; the broader refactor plan trims them.

set -euo pipefail

LIMIT=${HI_FILE_LINE_LIMIT:-800}
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

offenders=""
count=0

# Walk crate sources, excluding obvious generated-code paths.
while IFS= read -r f; do
    # Skip files whose opening lines mark them as generated.
    if head -n 5 "$f" | grep -Eq 'DO NOT EDIT|@generated|<auto-generated|Code generated'; then
        continue
    fi
    lines=$(wc -l < "$f" | tr -d ' ')
    if [ "$lines" -gt "$LIMIT" ]; then
        rel=${f#"$ROOT/"}
        offenders="${offenders}$(printf '%8d  %s\n' "$lines" "$rel")"
        count=$((count + 1))
    fi
done < <(find "$ROOT/crates" -path '*/src/*.rs' -type f \
    ! -path '*/gen/*' \
    ! -path '*/target/*' \
    | sort)

if [ "$count" -gt 0 ]; then
    printf 'Files exceeding %d lines (factor instead of appending):\n\n' "$LIMIT"
    printf '%s' "$offenders"
    printf '\n%d file(s) over the limit.\n' "$count"
    exit 1
fi

printf 'All crate source files are within the %d-line limit.\n' "$LIMIT"
