#!/usr/bin/env bash
# Core source-file line-count ratchet. Existing large files may shrink but may
# not grow; new files must stay within HI_FILE_LINE_LIMIT (default 800).
set -euo pipefail

LIMIT=${HI_FILE_LINE_LIMIT:-800}
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASELINE="$ROOT/scripts/file_size_baseline.txt"

if [ ! -f "$BASELINE" ]; then
    printf 'Missing file-size baseline: %s\n' "$BASELINE" >&2
    exit 2
fi

declare -A allowed=()
while read -r lines path; do
    case "$lines" in
        ''|'#'*) continue ;;
    esac
    allowed["$path"]=$lines
done < "$BASELINE"

failures=""
count=0
while IFS= read -r file; do
    if head -n 5 "$file" | grep -Eq 'DO NOT EDIT|@generated|<auto-generated|Code generated'; then
        continue
    fi
    rel=${file#"$ROOT/"}
    lines=$(wc -l < "$file" | tr -d ' ')
    ceiling=${allowed[$rel]:-$LIMIT}
    if [ "$lines" -gt "$ceiling" ]; then
        printf -v failure '%8d > %-8d %s' "$lines" "$ceiling" "$rel"
        failures+="${failure}"$'\n'
        count=$((count + 1))
    fi
done < <(
    find \
      "$ROOT/crates/hi-ai/src" \
      "$ROOT/crates/hi-tools/src" \
      "$ROOT/crates/hi-lsp/src" \
      "$ROOT/crates/hi-rsi-runtime/src" \
      "$ROOT/crates/hi-trace/src" \
      "$ROOT/crates/hi-agent/src" \
      "$ROOT/crates/hi-tui/src" \
      "$ROOT/crates/hi-cli/src" \
      "$ROOT/crates/hi-eval/src" \
      -type f -name '*.rs' ! -path '*/gen/*' | sort
)

if [ "$count" -gt 0 ]; then
    printf 'Core source files exceeded their line-count ceiling:\n\n%s' "$failures" >&2
    printf '\n%d file(s) grew beyond the ratchet. Factor code or deliberately update the baseline.\n' "$count" >&2
    exit 1
fi

printf 'Core source file-size ratchet passed (new-file limit %d lines).\n' "$LIMIT"
