//! Shared git-worktree helpers for isolated subprocess runs: best-of candidates
//! and the write-capable `delegate` subagent. A child `hi` works in a detached
//! worktree checked out to some base commit; on success only its verified diff
//! (relative to that base) is applied back to the real working tree.

use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Mutex;

use anyhow::{Context, Result, bail};

/// Pathspecs that keep Python bytecode caches out of merge staging/diffs. A
/// `.pyc` is regenerated by any test run and can end up tracked in a checkpoint
/// base (`git add -A`); excluding it keeps worktree merges to real source
/// changes instead of churning cache files. `glob` magic makes `**` span
/// directories; the trailing `**` also matches a top-level `__pycache__/`.
const PYCACHE_EXCLUDES: &[&str] = &[
    ":(exclude,glob)**/__pycache__/**",
    ":(exclude,glob)**/*.pyc",
    ":(exclude,glob)**/*.pyo",
];

/// Serializes merges into the shared working tree. Two isolated runs going loud
/// at once (e.g. two auto-fix loops) would otherwise `git apply` into the same
/// files concurrently and interleave writes. A plain `std::sync::Mutex` (these
/// helpers are synchronous), held only across the real-tree apply.
static MERGE_LOCK: Mutex<()> = Mutex::new(());

/// Whether `root` is inside a git work tree.
pub fn in_git_repo(root: &Path) -> bool {
    Command::new("git")
        .arg("-C")
        .arg(root)
        .args(["rev-parse", "--is-inside-work-tree"])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// A temp worktree path, namespaced by a caller `prefix` + `index`.
pub fn worktree_path(prefix: &str, index: u32) -> PathBuf {
    std::env::temp_dir().join(format!("hi-{prefix}-{}-{index}", std::process::id()))
}

/// Create a detached worktree at `path` checked out to `base` (a commit-ish).
pub fn add_worktree(repo_root: &Path, path: &Path, base: &str) -> Result<()> {
    let output = Command::new("git")
        .arg("-C")
        .arg(repo_root)
        .args(["worktree", "add", "--detach"])
        .arg(path)
        .arg(base)
        .output()
        .context("running git worktree add")?;
    if !output.status.success() {
        bail!(
            "git worktree add failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Fast CoW worktree — copy-on-write worktree creation using reflink cloning.
//
// Inspired by grok-build's `xai-fast-worktree` crate. Uses `reflink-copy` to
// clone files with CoW on supported filesystems (APFS on macOS, Btrfs/XFS on
// Linux), falling back to regular copy elsewhere. This is near-instant and
// disk-free compared to `git worktree add`, which checks out every file.
//
// The CoW worktree is a plain directory copy of the source tree (tracked files
// only, or tracked + dirty files), with a `.git` file pointing back to the
// source repository's git dir. It's suitable for isolated delegate/subagent
// execution where the child needs a writable copy but doesn't need a full git
// worktree's branch isolation.
// ---------------------------------------------------------------------------

/// How the CoW worktree was created — for diagnostics and fallback reporting.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum WorktreeMethod {
    /// CoW reflink (APFS clonefile / Linux FICLONE).
    Cow,
    /// Regular file copy (filesystem doesn't support reflink).
    FallbackCopy,
}

/// Plan for creating a CoW worktree.
#[derive(Clone, Debug)]
pub struct WorktreePlan {
    /// Source repository root (the real working tree).
    pub source: PathBuf,
    /// Target path for the new worktree.
    pub target: PathBuf,
    /// Skip files matched by `.gitignore` (and global gitignore).
    pub skip_ignored: bool,
    /// Also copy dirty (uncommitted) file content from the working tree,
    /// not just the git-tracked version. Default: true.
    pub copy_dirty: bool,
}

/// Result of creating a CoW worktree.
#[derive(Clone, Debug)]
pub struct CreateWorktreeResult {
    /// The path where the worktree was created (= `plan.target`).
    pub path: PathBuf,
    /// How files were copied.
    pub method: WorktreeMethod,
    /// Number of files copied.
    pub files_copied: usize,
}

impl WorktreePlan {
    /// Create a plan that copies all tracked + dirty files from `source` to
    /// `target`, skipping ignored files.
    pub fn new(source: impl Into<PathBuf>, target: impl Into<PathBuf>) -> Self {
        Self {
            source: source.into(),
            target: target.into(),
            skip_ignored: true,
            copy_dirty: true,
        }
    }

    /// Don't copy ignored files (only tracked + dirty). Default is `true`.
    pub fn skip_ignored(mut self, skip: bool) -> Self {
        self.skip_ignored = skip;
        self
    }

    /// Whether to copy uncommitted file content (dirty working tree state).
    pub fn copy_dirty(mut self, copy: bool) -> Self {
        self.copy_dirty = copy;
        self
    }
}

/// Create a CoW worktree from `plan`.
///
/// Walks the source tree (respecting `.gitignore` when `skip_ignored`), clones
/// each file with `reflink_or_copy`, recreates symlinks, and writes a `.git`
/// file pointing back to the source repo's git directory.
pub fn create_cow_worktree(plan: &WorktreePlan) -> Result<CreateWorktreeResult> {
    let source = plan.source.canonicalize().context("canonicalizing source")?;
    let target = &plan.target;

    // Find the source repo's .git directory (handles linked worktrees).
    let git_dir = find_git_dir(&source)?;

    std::fs::create_dir_all(target).context("creating target directory")?;

    // Walk the source tree manually (avoids the `ignore` crate's internal
    // .git directory traversal which can fail on repos with long pack paths).
    let gitignore = if plan.skip_ignored {
        build_gitignore(&source)
    } else {
        None
    };

    let mut files_copied = 0usize;
    let mut method = WorktreeMethod::Cow;

    copy_tree(&source, &source, target, target, gitignore.as_ref(), &mut files_copied, &mut method)?;

    // Write a .git file pointing to the source repo's git directory.
    // This makes the CoW worktree act as a git worktree for git commands.
    let git_file = target.join(".git");
    let git_dir_abs = if git_dir.is_absolute() {
        git_dir
    } else {
        source.join(&git_dir)
    };
    std::fs::write(&git_file, format!("gitdir: {}\n", git_dir_abs.display()))
        .context("writing .git file")?;

    Ok(CreateWorktreeResult {
        path: target.clone(),
        method,
        files_copied,
    })
}

/// Recursively copy a directory tree using CoW (reflink) with fallback to
/// regular copy. Skips `.git` at the root level and respects gitignore.
fn copy_tree(
    root: &Path,
    src: &Path,
    dest: &Path,
    skip_dest: &Path,
    gitignore: Option<&ignore::gitignore::Gitignore>,
    files_copied: &mut usize,
    method: &mut WorktreeMethod,
) -> Result<()> {
    for entry in std::fs::read_dir(src).context("reading source directory")? {
        let entry = entry?;
        let path = entry.path();
        let rel = path.strip_prefix(root).unwrap_or(&path);
        let dest_path = dest.join(rel);

        // Skip .git at the root level.
        if rel == std::path::Path::new(".git") {
            continue;
        }

        let file_type = entry.file_type()?;

        if file_type.is_symlink() {
            // Check gitignore.
            if let Some(gi) = gitignore {
                if is_ignored(gi, root, &path) {
                    continue;
                }
            }
            let target_link = std::fs::read_link(&path).context("reading symlink")?;
            let _ = std::fs::remove_file(&dest_path);
            #[cfg(unix)]
            std::os::unix::fs::symlink(&target_link, &dest_path).context("creating symlink")?;
            *files_copied += 1;
        } else if file_type.is_dir() {
            // Skip the target directory if it's inside the source (prevents
            // infinite recursion when target is a subdirectory of source).
            if dest_path == *skip_dest {
                continue;
            }
            std::fs::create_dir_all(&dest_path).context("creating directory")?;
            copy_tree(root, &path, &dest_path, skip_dest, gitignore, files_copied, method)?;
        } else if file_type.is_file() {
            // Check gitignore.
            if let Some(gi) = gitignore {
                if is_ignored(gi, root, &path) {
                    continue;
                }
            }
            // Ensure parent directory exists.
            if let Some(parent) = dest_path.parent() {
                std::fs::create_dir_all(parent).context("creating parent directory")?;
            }
            // Remove dest if it exists — reflink fails on existing files.
            let _ = std::fs::remove_file(&dest_path);
            // Try CoW first; fall back to regular copy.
            match reflink_copy::reflink_or_copy(&path, &dest_path) {
                Ok(_) => {}
                Err(e) => {
                    *method = WorktreeMethod::FallbackCopy;
                    return Err(anyhow::anyhow!("copying file {path:?} -> {dest_path:?}: {e}"));
                }
            }
            // Propagate permissions (reflink doesn't always preserve mode).
            let perms = std::fs::metadata(&path)?.permissions();
            std::fs::set_permissions(&dest_path, perms)?;
            *files_copied += 1;
        }
    }
    Ok(())
}

/// Build a gitignore matcher from the source repo's `.gitignore` file.
/// Returns `None` if no `.gitignore` exists or it can't be parsed.
fn build_gitignore(source: &Path) -> Option<ignore::gitignore::Gitignore> {
    let gitignore_path = source.join(".gitignore");
    if !gitignore_path.exists() {
        return None;
    }
    let mut builder = ignore::gitignore::GitignoreBuilder::new(source);
    if let Ok(content) = std::fs::read_to_string(&gitignore_path) {
        for line in content.lines() {
            // Skip comments and empty lines.
            let line = line.trim();
            if !line.is_empty() && !line.starts_with('#') {
                let _ = builder.add_line(None, line);
            }
        }
    }
    builder.build().ok()
}

/// Check if a path is ignored by the gitignore matcher.
fn is_ignored(gi: &ignore::gitignore::Gitignore, root: &Path, path: &Path) -> bool {
    let rel = path.strip_prefix(root).unwrap_or(path);
    gi.matched(rel, false).is_ignore()
}

/// Find the `.git` directory for a repository, handling linked worktrees.
/// Returns the path written in the `.git` file (for linked worktrees) or
/// `.git` itself for a standard repo.
fn find_git_dir(repo_root: &Path) -> Result<PathBuf> {
    let dot_git = repo_root.join(".git");
    if !dot_git.exists() {
        bail!("not a git repository: no .git in {}", repo_root.display());
    }
    if dot_git.is_file() {
        // Linked worktree: .git contains "gitdir: /path/to/real/gitdir"
        let content = std::fs::read_to_string(&dot_git).context("reading .git file")?;
        let line = content.trim();
        if let Some(rest) = line.strip_prefix("gitdir:") {
            return Ok(PathBuf::from(rest.trim()));
        }
    }
    Ok(PathBuf::from(".git"))
}

/// Remove a CoW worktree directory. Safe to call even if it wasn't created by
/// `create_cow_worktree` — it just removes the directory tree.
pub fn remove_cow_worktree(path: &Path) -> Result<()> {
    if path.exists() {
        std::fs::remove_dir_all(path).context("removing CoW worktree")?;
    }
    Ok(())
}

/// Ground-truth check: run the verify command inside the worktree.
pub fn verify_passes(worktree: &Path, verify: &str) -> bool {
    crate::prepare_verify_workdir(worktree);
    Command::new("sh")
        .arg("-c")
        .arg(verify)
        .env("PYTHONDONTWRITEBYTECODE", "1")
        .current_dir(worktree)
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Apply changes to an explicit destination repository root. This avoids any
/// dependency on the process cwd and is the preferred runtime API.
pub fn apply_changes_to(worktree: &Path, base: &str, destination_root: &Path) -> Result<bool> {
    apply_changes_impl(worktree, base, destination_root)
}

fn apply_changes_impl(worktree: &Path, base: &str, destination_root: &Path) -> Result<bool> {
    // Strip Python bytecode caches the child's own test runs left behind, and
    // exclude them from the staging/diff below: a firing (or the child's test
    // run) regenerates `__pycache__/*.pyc`, and because `checkpoint::create`
    // snapshots the whole tree with `add -A` the cache can be tracked in `base`
    // — so it otherwise churns through the diff as noise (or a spurious
    // deleted-file merge / unappliable binary patch). Real source only merges.
    crate::prepare_verify_workdir(worktree);
    // Stage everything (minus pycache) so the diff captures new/deleted files.
    let add = Command::new("git")
        .current_dir(worktree)
        .args(["add", "-A", "--", "."])
        .args(PYCACHE_EXCLUDES)
        .output()
        .context("git add in worktree")?;
    if !add.status.success() {
        bail!(
            "git add failed: {}",
            String::from_utf8_lossy(&add.stderr).trim()
        );
    }

    let diff = Command::new("git")
        .current_dir(worktree)
        // --binary so legitimate binary assets (images, fixtures) survive the
        // pipe to `git apply` instead of arriving as "Binary files differ".
        .args(["diff", "--cached", "--binary", base, "--"])
        .args(PYCACHE_EXCLUDES)
        .output()
        .context("git diff in worktree")?;
    if !diff.status.success() {
        bail!(
            "git diff failed: {}",
            String::from_utf8_lossy(&diff.stderr).trim()
        );
    }
    if diff.stdout.is_empty() {
        return Ok(false); // nothing changed
    }

    // Apply the patch in the main repo via stdin. Capture stderr so a failed
    // apply says *which file/hunk* conflicted — in the TUI the inherited stderr
    // is invisible, which made fleet merge failures undiagnosable.
    use std::io::Write;
    // Serialize the real-tree apply (MERGE_LOCK) and run it from the repo root so
    // repo-root-relative patch paths resolve regardless of the launch cwd. The
    // guard is held until this function returns (through the write + wait below).
    let _merge = MERGE_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    let mut apply = Command::new("git");
    apply.args(["apply", "--whitespace=nowarn"]);
    apply.current_dir(destination_root);
    let mut child = apply
        .stdin(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .context("spawning git apply")?;
    child
        .stdin
        .take()
        .context("git apply stdin")?
        .write_all(&diff.stdout)
        .context("writing patch to git apply")?;
    let out = child.wait_with_output().context("waiting for git apply")?;
    if !out.status.success() {
        let why = String::from_utf8_lossy(&out.stderr);
        let why = why.trim();
        bail!(
            "git apply failed: {}",
            if why.is_empty() {
                "working tree may conflict with the patch"
            } else {
                why
            }
        );
    }
    Ok(true)
}

/// The files the worktree changed relative to `base` (staged first so new/deleted
/// files are included). Python bytecode caches are stripped first so they don't
/// show up as phantom changes (or trigger spurious overlap holds in the fleet).
pub fn changed_files(worktree: &Path, base: &str) -> Vec<String> {
    crate::prepare_verify_workdir(worktree);
    let _ = Command::new("git")
        .current_dir(worktree)
        .args(["add", "-A", "--", "."])
        .args(PYCACHE_EXCLUDES)
        .output();
    Command::new("git")
        .current_dir(worktree)
        .args(["diff", "--cached", "--name-only", base, "--"])
        .args(PYCACHE_EXCLUDES)
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| {
            String::from_utf8_lossy(&o.stdout)
                .lines()
                .map(str::to_string)
                .filter(|l| !l.is_empty())
                .collect()
        })
        .unwrap_or_default()
}

/// Commit all of the worktree's changes (minus pycache) onto a fresh `branch`
/// created from its current base. Used by auto-fix's PR mode to prepare a
/// reviewable branch instead of merging into the working tree. Uses the repo's
/// configured author identity.
pub fn commit_to_branch(worktree: &Path, branch: &str, message: &str) -> Result<()> {
    let checkout = Command::new("git")
        .current_dir(worktree)
        .args(["checkout", "-b", branch])
        .output()
        .context("git checkout -b")?;
    if !checkout.status.success() {
        bail!(
            "git checkout -b failed: {}",
            String::from_utf8_lossy(&checkout.stderr).trim()
        );
    }
    crate::prepare_verify_workdir(worktree);
    let add = Command::new("git")
        .current_dir(worktree)
        .args(["add", "-A", "--", "."])
        .args(PYCACHE_EXCLUDES)
        .output()
        .context("git add")?;
    if !add.status.success() {
        bail!(
            "git add failed: {}",
            String::from_utf8_lossy(&add.stderr).trim()
        );
    }
    let commit = Command::new("git")
        .current_dir(worktree)
        .args(["commit", "-m", message])
        .output()
        .context("git commit")?;
    if !commit.status.success() {
        bail!(
            "git commit failed: {}",
            String::from_utf8_lossy(&commit.stderr).trim()
        );
    }
    Ok(())
}

/// Push a worktree branch to `origin`, setting upstream. Returns an error (with
/// git's stderr) if there's no remote or the push is rejected.
pub fn push_branch(worktree: &Path, branch: &str) -> Result<()> {
    let out = Command::new("git")
        .current_dir(worktree)
        .args(["push", "-u", "origin", branch])
        .output()
        .context("git push")?;
    if !out.status.success() {
        bail!(
            "git push failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    Ok(())
}

/// Force-remove the given worktrees.
pub fn cleanup(repo_root: &Path, worktrees: &[PathBuf]) {
    for path in worktrees {
        let _ = Command::new("git")
            .arg("-C")
            .arg(repo_root)
            .args(["worktree", "remove", "--force"])
            .arg(path)
            .output();
    }
}

/// Hard-reset a worktree onto a new base commit (fleet rebase: adopt a fresh
/// snapshot of the real tree, discarding the worktree's current state — callers
/// must ensure nothing unmerged is lost first).
pub fn reset_to(worktree: &Path, base: &str) -> Result<()> {
    let out = Command::new("git")
        .args(["reset", "--hard", base])
        .current_dir(worktree)
        .output()
        .context("running git reset in the worktree")?;
    if !out.status.success() {
        bail!(
            "git reset --hard {base} failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Serializes tests that mutate the process cwd (`apply_changes` targets the
    /// cwd), so they don't race under parallel execution.
    static CWD_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    /// Python bytecode caches left by a child's test runs must not enter the
    /// diff: they made `git apply` fail (binary) and polluted overlap sets.
    #[test]
    fn pycache_is_stripped_from_changes_and_apply() {
        let _cwd = CWD_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let dir = std::env::temp_dir().join(format!("hi-wt-pyc-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let git = |args: &[&str], cwd: &Path| {
            let out = Command::new("git")
                .args(args)
                .current_dir(cwd)
                .output()
                .unwrap();
            assert!(
                out.status.success(),
                "git {args:?}: {}",
                String::from_utf8_lossy(&out.stderr)
            );
        };
        git(&["init", "-q"], &dir);
        std::fs::write(dir.join("a.py"), "x = 1\n").unwrap();
        git(&["add", "-A"], &dir);
        git(
            &[
                "-c",
                "user.email=t@t",
                "-c",
                "user.name=t",
                "commit",
                "-qm",
                "c1",
            ],
            &dir,
        );
        let wt = dir.join("wt");
        git(
            &["worktree", "add", "-q", wt.to_str().unwrap(), "HEAD"],
            &dir,
        );
        // The "agent" edits a.py AND its test run drops binary bytecode.
        std::fs::write(wt.join("a.py"), "x = 2\n").unwrap();
        std::fs::create_dir_all(wt.join("__pycache__")).unwrap();
        std::fs::write(wt.join("__pycache__/a.cpython-312.pyc"), b"\x00\x01junk").unwrap();

        let changed = changed_files(&wt, "HEAD");
        assert_eq!(
            changed,
            vec!["a.py"],
            "pycache must not appear: {changed:?}"
        );
        // Apply must succeed (before the fix the binary .pyc broke git apply)
        // — run it from the main repo dir, as callers do.
        let applied = apply_changes_to(&wt, "HEAD", &dir);
        assert!(applied.expect("apply ok"), "expected a change applied");
        assert_eq!(
            std::fs::read_to_string(dir.join("a.py")).unwrap(),
            "x = 2\n"
        );

        cleanup(&dir, &[wt]);
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// The merge `git apply` must run from the repo root even when `hi` was
    /// launched from a subdirectory — patch paths are repo-root-relative, so a
    /// subdir cwd used to break the merge (git apply looked under the subdir).
    #[test]
    fn apply_changes_merges_from_a_subdirectory_cwd() {
        let _cwd = CWD_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let dir = std::env::temp_dir().join(format!("hi-wt-subdir-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let git = |args: &[&str], cwd: &Path| {
            let out = Command::new("git")
                .args(args)
                .current_dir(cwd)
                .output()
                .unwrap();
            assert!(
                out.status.success(),
                "git {args:?}: {}",
                String::from_utf8_lossy(&out.stderr)
            );
        };
        git(&["init", "-q"], &dir);
        std::fs::create_dir_all(dir.join("sub")).unwrap();
        std::fs::write(dir.join("src.txt"), "one\n").unwrap();
        git(&["add", "-A"], &dir);
        git(
            &[
                "-c",
                "user.email=t@t",
                "-c",
                "user.name=t",
                "commit",
                "-qm",
                "c1",
            ],
            &dir,
        );
        let wt = dir.join("wt");
        git(
            &["worktree", "add", "-q", wt.to_str().unwrap(), "HEAD"],
            &dir,
        );
        std::fs::write(wt.join("src.txt"), "two\n").unwrap();

        let applied = apply_changes_to(&wt, "HEAD", &dir);

        assert!(
            applied.expect("apply ok from a subdir cwd"),
            "a change applied"
        );
        assert_eq!(
            std::fs::read_to_string(dir.join("src.txt")).unwrap(),
            "two\n"
        );

        cleanup(&dir, &[wt]);
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// The harder case a live auto-fix run hit: `__pycache__` is *tracked in the
    /// base* (a firing left a `.pyc` and `checkpoint::create`'s `git add -A`
    /// captured it), so stripping the worktree copy turns it into a spurious
    /// deleted-file in the diff. The pathspec exclusion must keep it out entirely
    /// — the merge is source-only and the real tree's cache is left alone.
    #[test]
    fn pycache_tracked_in_base_is_excluded_from_merge() {
        let _cwd = CWD_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let dir = std::env::temp_dir().join(format!("hi-wt-pyc2-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let git = |args: &[&str], cwd: &Path| {
            let out = Command::new("git")
                .args(args)
                .current_dir(cwd)
                .output()
                .unwrap();
            assert!(
                out.status.success(),
                "git {args:?}: {}",
                String::from_utf8_lossy(&out.stderr)
            );
        };
        git(&["init", "-q"], &dir);
        std::fs::write(dir.join("a.py"), "x = 1\n").unwrap();
        // The base tracks a .pyc (as checkpoint's `add -A` would after a firing).
        std::fs::create_dir_all(dir.join("__pycache__")).unwrap();
        std::fs::write(dir.join("__pycache__/a.cpython-312.pyc"), b"\x00old").unwrap();
        git(&["add", "-A"], &dir);
        git(
            &[
                "-c",
                "user.email=t@t",
                "-c",
                "user.name=t",
                "commit",
                "-qm",
                "c1",
            ],
            &dir,
        );
        let wt = dir.join("wt");
        git(
            &["worktree", "add", "-q", wt.to_str().unwrap(), "HEAD"],
            &dir,
        );
        // The agent edits a.py and its test run regenerates the tracked .pyc.
        std::fs::write(wt.join("a.py"), "x = 2\n").unwrap();
        std::fs::write(wt.join("__pycache__/a.cpython-312.pyc"), b"\x00new").unwrap();

        let changed = changed_files(&wt, "HEAD");
        assert_eq!(
            changed,
            vec!["a.py"],
            "tracked pyc must not churn: {changed:?}"
        );

        let applied = apply_changes_to(&wt, "HEAD", &dir);
        assert!(
            applied.expect("apply ok"),
            "expected a source change applied"
        );
        assert_eq!(
            std::fs::read_to_string(dir.join("a.py")).unwrap(),
            "x = 2\n"
        );
        // The real tree's cache is untouched — not merged, not deleted.
        assert_eq!(
            std::fs::read(dir.join("__pycache__/a.cpython-312.pyc")).unwrap(),
            b"\x00old",
            "the base's .pyc must be left alone"
        );

        cleanup(&dir, &[wt]);
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// Auto-fix PR mode's git plumbing over a real repo + local bare remote: a
    /// worktree change commits onto a fresh branch (minus pycache) and pushes to
    /// origin. No cwd mutation, no gh, no network.
    #[test]
    fn commit_to_branch_and_push_lands_a_fix_branch() {
        let root = std::env::temp_dir().join(format!("hi-wt-pr-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).unwrap();
        let bare = root.join("remote.git");
        let repo = root.join("repo");
        let git = |args: &[&str], cwd: &Path| {
            let out = Command::new("git")
                .args(args)
                .current_dir(cwd)
                .output()
                .unwrap();
            assert!(
                out.status.success(),
                "git {args:?}: {}",
                String::from_utf8_lossy(&out.stderr)
            );
        };
        git(&["init", "--bare", "-q", bare.to_str().unwrap()], &root);
        git(&["init", "-q", "-b", "main", repo.to_str().unwrap()], &root);
        git(&["config", "user.email", "t@t"], &repo);
        git(&["config", "user.name", "t"], &repo);
        git(&["remote", "add", "origin", bare.to_str().unwrap()], &repo);
        std::fs::write(repo.join("a.py"), "x = 1\n").unwrap();
        git(&["add", "-A"], &repo);
        git(&["commit", "-qm", "c1"], &repo);

        let wt = repo.join("wt");
        git(
            &["worktree", "add", "-q", wt.to_str().unwrap(), "HEAD"],
            &repo,
        );
        // The fix edits a.py and its test run drops bytecode (must not be committed).
        std::fs::write(wt.join("a.py"), "x = 2\n").unwrap();
        std::fs::create_dir_all(wt.join("__pycache__")).unwrap();
        std::fs::write(wt.join("__pycache__/a.cpython-312.pyc"), b"junk").unwrap();

        commit_to_branch(&wt, "hi-autofix/loop1", "hi auto-fix: a").expect("commit ok");
        push_branch(&wt, "hi-autofix/loop1").expect("push ok");

        // The branch landed in the bare remote…
        let show = Command::new("git")
            .current_dir(&bare)
            .args(["rev-parse", "--verify", "hi-autofix/loop1"])
            .output()
            .unwrap();
        assert!(show.status.success(), "branch must exist in the remote");
        // …with the source change but not the pycache.
        let files = Command::new("git")
            .current_dir(&bare)
            .args(["ls-tree", "-r", "--name-only", "hi-autofix/loop1"])
            .output()
            .unwrap();
        let files = String::from_utf8_lossy(&files.stdout);
        assert!(files.contains("a.py"), "a.py committed: {files}");
        assert!(!files.contains(".pyc"), "no pycache in the branch: {files}");

        cleanup(&repo, &[wt]);
        let _ = std::fs::remove_dir_all(&root);
    }

    /// End-to-end reset_to: a worktree with local edits hard-resets onto a new
    /// base commit, discarding its state and adopting the new snapshot.
    #[test]
    fn reset_to_adopts_a_new_base() {
        let dir = std::env::temp_dir().join(format!("hi-wt-reset-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let git = |args: &[&str], cwd: &Path| {
            let out = Command::new("git")
                .args(args)
                .current_dir(cwd)
                .output()
                .unwrap();
            assert!(
                out.status.success(),
                "git {args:?}: {}",
                String::from_utf8_lossy(&out.stderr)
            );
            String::from_utf8_lossy(&out.stdout).trim().to_string()
        };
        git(&["init", "-q"], &dir);
        std::fs::write(dir.join("a.txt"), "one\n").unwrap();
        git(&["add", "-A"], &dir);
        git(
            &[
                "-c",
                "user.email=t@t",
                "-c",
                "user.name=t",
                "commit",
                "-qm",
                "c1",
            ],
            &dir,
        );
        let wt = dir.join("wt");
        git(
            &["worktree", "add", "-q", wt.to_str().unwrap(), "HEAD"],
            &dir,
        );
        // Dirty the worktree, then advance the base in the main repo.
        std::fs::write(wt.join("a.txt"), "dirty\n").unwrap();
        std::fs::write(dir.join("a.txt"), "two\n").unwrap();
        git(&["add", "-A"], &dir);
        git(
            &[
                "-c",
                "user.email=t@t",
                "-c",
                "user.name=t",
                "commit",
                "-qm",
                "c2",
            ],
            &dir,
        );
        let new_base = git(&["rev-parse", "HEAD"], &dir);

        reset_to(&wt, &new_base).expect("reset succeeds");
        assert_eq!(std::fs::read_to_string(wt.join("a.txt")).unwrap(), "two\n");

        cleanup(&dir, &[wt]);
        let _ = std::fs::remove_dir_all(&dir);
    }

    // --- CoW worktree tests ---

    fn make_git_repo(dir: &Path) {
        let git = |args: &[&str], cwd: &Path| {
            let out = Command::new("git").args(args).current_dir(cwd).output().unwrap();
            assert!(out.status.success(), "git {args:?}: {}", String::from_utf8_lossy(&out.stderr));
        };
        git(&["init", "-q"], dir);
        git(&["config", "user.email", "t@t"], dir);
        git(&["config", "user.name", "t"], dir);
    }

    fn git_commit(dir: &Path, msg: &str) {
        let git = |args: &[&str], cwd: &Path| {
            let out = Command::new("git").args(args).current_dir(cwd).output().unwrap();
            assert!(out.status.success(), "git {args:?}: {}", String::from_utf8_lossy(&out.stderr));
        };
        git(&["add", "-A"], dir);
        git(&["commit", "-qm", msg], dir);
    }

    #[test]
    fn cow_worktree_copies_tracked_files() {
        let dir = std::env::temp_dir().join(format!("hi-cow-basic-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        make_git_repo(&dir);
        std::fs::write(dir.join("a.txt"), "alpha\n").unwrap();
        std::fs::write(dir.join("b.txt"), "beta\n").unwrap();
        git_commit(&dir, "c1");

        let target = std::env::temp_dir().join(format!("hi-cow-basic-wt-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&target);
        let plan = WorktreePlan::new(&dir, &target);
        let result = create_cow_worktree(&plan).expect("cow worktree created");

        assert!(result.path.exists());
        assert!(result.files_copied >= 2, "copied {} files", result.files_copied);
        assert_eq!(std::fs::read_to_string(target.join("a.txt")).unwrap(), "alpha\n");
        assert_eq!(std::fs::read_to_string(target.join("b.txt")).unwrap(), "beta\n");
        // .git file should point back to the source repo.
        assert!(target.join(".git").is_file(), ".git file exists");

        let _ = std::fs::remove_dir_all(&dir);
        let _ = std::fs::remove_dir_all(&target);
    }

    #[test]
    fn cow_worktree_skips_ignored_files() {
        let dir = std::env::temp_dir().join(format!("hi-cow-ignore-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        make_git_repo(&dir);
        std::fs::write(dir.join("tracked.txt"), "yes\n").unwrap();
        std::fs::write(dir.join(".env"), "SECRET=abc\n").unwrap();
        std::fs::write(dir.join(".gitignore"), ".env\n").unwrap();
        git_commit(&dir, "c1");

        let target = std::env::temp_dir().join(format!("hi-cow-ignore-wt-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&target);
        let plan = WorktreePlan::new(&dir, &target).skip_ignored(true);
        let _ = create_cow_worktree(&plan).expect("cow worktree created");

        assert!(target.join("tracked.txt").exists(), "tracked file copied");
        assert!(!target.join(".env").exists(), ".env should be skipped (gitignored)");

        let _ = std::fs::remove_dir_all(&dir);
        let _ = std::fs::remove_dir_all(&target);
    }

    #[test]
    fn cow_worktree_preserves_symlinks() {
        let dir = std::env::temp_dir().join(format!("hi-cow-sym-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        make_git_repo(&dir);
        std::fs::write(dir.join("real.txt"), "content\n").unwrap();
        #[cfg(unix)]
        std::os::unix::fs::symlink("real.txt", dir.join("link.txt")).unwrap();
        git_commit(&dir, "c1");

        let target = std::env::temp_dir().join(format!("hi-cow-sym-wt-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&target);
        let plan = WorktreePlan::new(&dir, &target);
        let _ = create_cow_worktree(&plan).expect("cow worktree created");

        #[cfg(unix)]
        {
            let meta = std::fs::symlink_metadata(target.join("link.txt")).unwrap();
            assert!(meta.file_type().is_symlink(), "symlink recreated");
            assert_eq!(
                std::fs::read_link(target.join("link.txt")).unwrap(),
                std::path::Path::new("real.txt")
            );
        }

        let _ = std::fs::remove_dir_all(&dir);
        let _ = std::fs::remove_dir_all(&target);
    }

    #[test]
    fn cow_worktree_preserves_executable_bit() {
        use std::os::unix::fs::PermissionsExt;
        let dir = std::env::temp_dir().join(format!("hi-cow-exec-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        make_git_repo(&dir);
        std::fs::write(dir.join("script.sh"), "#!/bin/sh\necho hi\n").unwrap();
        let mut perms = std::fs::metadata(dir.join("script.sh")).unwrap().permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(dir.join("script.sh"), perms).unwrap();
        git_commit(&dir, "c1");

        let target = std::env::temp_dir().join(format!("hi-cow-exec-wt-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&target);
        let plan = WorktreePlan::new(&dir, &target);
        let _ = create_cow_worktree(&plan).expect("cow worktree created");

        let dest_perms = std::fs::metadata(target.join("script.sh")).unwrap().permissions();
        assert_eq!(dest_perms.mode() & 0o777, 0o755, "executable bit preserved");

        let _ = std::fs::remove_dir_all(&dir);
        let _ = std::fs::remove_dir_all(&target);
    }

    #[test]
    fn remove_cow_worktree_cleans_up() {
        let dir = std::env::temp_dir().join(format!("hi-cow-rm-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        make_git_repo(&dir);
        std::fs::write(dir.join("a.txt"), "a\n").unwrap();
        git_commit(&dir, "c1");

        let target = std::env::temp_dir().join(format!("hi-cow-rm-wt-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&target);
        let plan = WorktreePlan::new(&dir, &target);
        let _ = create_cow_worktree(&plan).unwrap();
        assert!(target.exists());

        remove_cow_worktree(&target).expect("removed");
        assert!(!target.exists(), "worktree removed");

        let _ = std::fs::remove_dir_all(&dir);
    }
}
