//! Shared git-worktree helpers for isolated subprocess runs: best-of candidates
//! and the write-capable `delegate` subagent. A child `hi` works in a detached
//! worktree checked out to some base commit; on success only its verified diff
//! (relative to that base) is applied back to the real working tree.

use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Mutex;

use anyhow::{Context, Result, bail};

/// Pathspecs that keep Python bytecode caches out of merge staging/diffs. A
/// `.pyc` is regenerated by any test run and can end up tracked in a checkpoint
/// base (`git add -A`); excluding it keeps worktree merges to real source
/// changes instead of churning cache files. `glob` magic makes `**` span
/// directories; the trailing `**` also matches a top-level `__pycache__/`.
const PYCACHE_EXCLUDES: &[&str] = &[
    ":(exclude,glob)**/__pycache__/**",
    ":(exclude,glob)**/*.pyc",
    ":(exclude,glob)**/*.pyo",
];

/// Serializes merges into the shared working tree. Two isolated runs going loud
/// at once (e.g. two auto-fix loops) would otherwise `git apply` into the same
/// files concurrently and interleave writes. A plain `std::sync::Mutex` (these
/// helpers are synchronous), held only across the real-tree apply.
static MERGE_LOCK: Mutex<()> = Mutex::new(());

/// Whether `root` is inside a git work tree.
pub fn in_git_repo(root: &Path) -> bool {
    Command::new("git")
        .arg("-C")
        .arg(root)
        .args(["rev-parse", "--is-inside-work-tree"])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// A temp worktree path, namespaced by a caller `prefix` + `index`.
pub fn worktree_path(prefix: &str, index: u32) -> PathBuf {
    std::env::temp_dir().join(format!("hi-{prefix}-{}-{index}", std::process::id()))
}

/// Create a detached worktree at `path` checked out to `base` (a commit-ish).
pub fn add_worktree(repo_root: &Path, path: &Path, base: &str) -> Result<()> {
    let output = Command::new("git")
        .arg("-C")
        .arg(repo_root)
        .args(["worktree", "add", "--detach"])
        .arg(path)
        .arg(base)
        .output()
        .context("running git worktree add")?;
    if !output.status.success() {
        bail!(
            "git worktree add failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    Ok(())
}

/// Ground-truth check: run the verify command inside the worktree.
pub fn verify_passes(worktree: &Path, verify: &str) -> bool {
    crate::prepare_verify_workdir(worktree);
    Command::new("sh")
        .arg("-c")
        .arg(verify)
        .env("PYTHONDONTWRITEBYTECODE", "1")
        .current_dir(worktree)
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Apply changes to an explicit destination repository root. This avoids any
/// dependency on the process cwd and is the preferred runtime API.
pub fn apply_changes_to(worktree: &Path, base: &str, destination_root: &Path) -> Result<bool> {
    apply_changes_impl(worktree, base, destination_root)
}

fn apply_changes_impl(worktree: &Path, base: &str, destination_root: &Path) -> Result<bool> {
    // Strip Python bytecode caches the child's own test runs left behind, and
    // exclude them from the staging/diff below: a firing (or the child's test
    // run) regenerates `__pycache__/*.pyc`, and because `checkpoint::create`
    // snapshots the whole tree with `add -A` the cache can be tracked in `base`
    // — so it otherwise churns through the diff as noise (or a spurious
    // deleted-file merge / unappliable binary patch). Real source only merges.
    crate::prepare_verify_workdir(worktree);
    // Stage everything (minus pycache) so the diff captures new/deleted files.
    let add = Command::new("git")
        .current_dir(worktree)
        .args(["add", "-A", "--", "."])
        .args(PYCACHE_EXCLUDES)
        .output()
        .context("git add in worktree")?;
    if !add.status.success() {
        bail!(
            "git add failed: {}",
            String::from_utf8_lossy(&add.stderr).trim()
        );
    }

    let diff = Command::new("git")
        .current_dir(worktree)
        // --binary so legitimate binary assets (images, fixtures) survive the
        // pipe to `git apply` instead of arriving as "Binary files differ".
        .args(["diff", "--cached", "--binary", base, "--"])
        .args(PYCACHE_EXCLUDES)
        .output()
        .context("git diff in worktree")?;
    if !diff.status.success() {
        bail!(
            "git diff failed: {}",
            String::from_utf8_lossy(&diff.stderr).trim()
        );
    }
    if diff.stdout.is_empty() {
        return Ok(false); // nothing changed
    }

    // Apply the patch in the main repo via stdin. Capture stderr so a failed
    // apply says *which file/hunk* conflicted — in the TUI the inherited stderr
    // is invisible, which made fleet merge failures undiagnosable.
    use std::io::Write;
    // Serialize the real-tree apply (MERGE_LOCK) and run it from the repo root so
    // repo-root-relative patch paths resolve regardless of the launch cwd. The
    // guard is held until this function returns (through the write + wait below).
    let _merge = MERGE_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    let mut apply = Command::new("git");
    apply.args(["apply", "--whitespace=nowarn"]);
    apply.current_dir(destination_root);
    let mut child = apply
        .stdin(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .context("spawning git apply")?;
    child
        .stdin
        .take()
        .context("git apply stdin")?
        .write_all(&diff.stdout)
        .context("writing patch to git apply")?;
    let out = child.wait_with_output().context("waiting for git apply")?;
    if !out.status.success() {
        let why = String::from_utf8_lossy(&out.stderr);
        let why = why.trim();
        bail!(
            "git apply failed: {}",
            if why.is_empty() {
                "working tree may conflict with the patch"
            } else {
                why
            }
        );
    }
    Ok(true)
}

/// The files the worktree changed relative to `base` (staged first so new/deleted
/// files are included). Python bytecode caches are stripped first so they don't
/// show up as phantom changes (or trigger spurious overlap holds in the fleet).
pub fn changed_files(worktree: &Path, base: &str) -> Vec<String> {
    crate::prepare_verify_workdir(worktree);
    let _ = Command::new("git")
        .current_dir(worktree)
        .args(["add", "-A", "--", "."])
        .args(PYCACHE_EXCLUDES)
        .output();
    Command::new("git")
        .current_dir(worktree)
        .args(["diff", "--cached", "--name-only", base, "--"])
        .args(PYCACHE_EXCLUDES)
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| {
            String::from_utf8_lossy(&o.stdout)
                .lines()
                .map(str::to_string)
                .filter(|l| !l.is_empty())
                .collect()
        })
        .unwrap_or_default()
}

/// Commit all of the worktree's changes (minus pycache) onto a fresh `branch`
/// created from its current base. Used by auto-fix's PR mode to prepare a
/// reviewable branch instead of merging into the working tree. Uses the repo's
/// configured author identity.
pub fn commit_to_branch(worktree: &Path, branch: &str, message: &str) -> Result<()> {
    let checkout = Command::new("git")
        .current_dir(worktree)
        .args(["checkout", "-b", branch])
        .output()
        .context("git checkout -b")?;
    if !checkout.status.success() {
        bail!(
            "git checkout -b failed: {}",
            String::from_utf8_lossy(&checkout.stderr).trim()
        );
    }
    crate::prepare_verify_workdir(worktree);
    let add = Command::new("git")
        .current_dir(worktree)
        .args(["add", "-A", "--", "."])
        .args(PYCACHE_EXCLUDES)
        .output()
        .context("git add")?;
    if !add.status.success() {
        bail!(
            "git add failed: {}",
            String::from_utf8_lossy(&add.stderr).trim()
        );
    }
    let commit = Command::new("git")
        .current_dir(worktree)
        .args(["commit", "-m", message])
        .output()
        .context("git commit")?;
    if !commit.status.success() {
        bail!(
            "git commit failed: {}",
            String::from_utf8_lossy(&commit.stderr).trim()
        );
    }
    Ok(())
}

/// Push a worktree branch to `origin`, setting upstream. Returns an error (with
/// git's stderr) if there's no remote or the push is rejected.
pub fn push_branch(worktree: &Path, branch: &str) -> Result<()> {
    let out = Command::new("git")
        .current_dir(worktree)
        .args(["push", "-u", "origin", branch])
        .output()
        .context("git push")?;
    if !out.status.success() {
        bail!(
            "git push failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    Ok(())
}

/// Force-remove the given worktrees.
pub fn cleanup(repo_root: &Path, worktrees: &[PathBuf]) {
    for path in worktrees {
        let _ = Command::new("git")
            .arg("-C")
            .arg(repo_root)
            .args(["worktree", "remove", "--force"])
            .arg(path)
            .output();
    }
}

/// Hard-reset a worktree onto a new base commit (fleet rebase: adopt a fresh
/// snapshot of the real tree, discarding the worktree's current state — callers
/// must ensure nothing unmerged is lost first).
pub fn reset_to(worktree: &Path, base: &str) -> Result<()> {
    let out = Command::new("git")
        .args(["reset", "--hard", base])
        .current_dir(worktree)
        .output()
        .context("running git reset in the worktree")?;
    if !out.status.success() {
        bail!(
            "git reset --hard {base} failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Serializes tests that mutate the process cwd (`apply_changes` targets the
    /// cwd), so they don't race under parallel execution.
    static CWD_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    /// Python bytecode caches left by a child's test runs must not enter the
    /// diff: they made `git apply` fail (binary) and polluted overlap sets.
    #[test]
    fn pycache_is_stripped_from_changes_and_apply() {
        let _cwd = CWD_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let dir = std::env::temp_dir().join(format!("hi-wt-pyc-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let git = |args: &[&str], cwd: &Path| {
            let out = Command::new("git")
                .args(args)
                .current_dir(cwd)
                .output()
                .unwrap();
            assert!(
                out.status.success(),
                "git {args:?}: {}",
                String::from_utf8_lossy(&out.stderr)
            );
        };
        git(&["init", "-q"], &dir);
        std::fs::write(dir.join("a.py"), "x = 1\n").unwrap();
        git(&["add", "-A"], &dir);
        git(
            &[
                "-c",
                "user.email=t@t",
                "-c",
                "user.name=t",
                "commit",
                "-qm",
                "c1",
            ],
            &dir,
        );
        let wt = dir.join("wt");
        git(
            &["worktree", "add", "-q", wt.to_str().unwrap(), "HEAD"],
            &dir,
        );
        // The "agent" edits a.py AND its test run drops binary bytecode.
        std::fs::write(wt.join("a.py"), "x = 2\n").unwrap();
        std::fs::create_dir_all(wt.join("__pycache__")).unwrap();
        std::fs::write(wt.join("__pycache__/a.cpython-312.pyc"), b"\x00\x01junk").unwrap();

        let changed = changed_files(&wt, "HEAD");
        assert_eq!(
            changed,
            vec!["a.py"],
            "pycache must not appear: {changed:?}"
        );
        // Apply must succeed (before the fix the binary .pyc broke git apply)
        // — run it from the main repo dir, as callers do.
        let applied = apply_changes_to(&wt, "HEAD", &dir);
        assert!(applied.expect("apply ok"), "expected a change applied");
        assert_eq!(
            std::fs::read_to_string(dir.join("a.py")).unwrap(),
            "x = 2\n"
        );

        cleanup(&dir, &[wt]);
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// The merge `git apply` must run from the repo root even when `hi` was
    /// launched from a subdirectory — patch paths are repo-root-relative, so a
    /// subdir cwd used to break the merge (git apply looked under the subdir).
    #[test]
    fn apply_changes_merges_from_a_subdirectory_cwd() {
        let _cwd = CWD_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let dir = std::env::temp_dir().join(format!("hi-wt-subdir-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let git = |args: &[&str], cwd: &Path| {
            let out = Command::new("git")
                .args(args)
                .current_dir(cwd)
                .output()
                .unwrap();
            assert!(
                out.status.success(),
                "git {args:?}: {}",
                String::from_utf8_lossy(&out.stderr)
            );
        };
        git(&["init", "-q"], &dir);
        std::fs::create_dir_all(dir.join("sub")).unwrap();
        std::fs::write(dir.join("src.txt"), "one\n").unwrap();
        git(&["add", "-A"], &dir);
        git(
            &[
                "-c",
                "user.email=t@t",
                "-c",
                "user.name=t",
                "commit",
                "-qm",
                "c1",
            ],
            &dir,
        );
        let wt = dir.join("wt");
        git(
            &["worktree", "add", "-q", wt.to_str().unwrap(), "HEAD"],
            &dir,
        );
        std::fs::write(wt.join("src.txt"), "two\n").unwrap();

        let applied = apply_changes_to(&wt, "HEAD", &dir);

        assert!(
            applied.expect("apply ok from a subdir cwd"),
            "a change applied"
        );
        assert_eq!(
            std::fs::read_to_string(dir.join("src.txt")).unwrap(),
            "two\n"
        );

        cleanup(&dir, &[wt]);
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// The harder case a live auto-fix run hit: `__pycache__` is *tracked in the
    /// base* (a firing left a `.pyc` and `checkpoint::create`'s `git add -A`
    /// captured it), so stripping the worktree copy turns it into a spurious
    /// deleted-file in the diff. The pathspec exclusion must keep it out entirely
    /// — the merge is source-only and the real tree's cache is left alone.
    #[test]
    fn pycache_tracked_in_base_is_excluded_from_merge() {
        let _cwd = CWD_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let dir = std::env::temp_dir().join(format!("hi-wt-pyc2-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let git = |args: &[&str], cwd: &Path| {
            let out = Command::new("git")
                .args(args)
                .current_dir(cwd)
                .output()
                .unwrap();
            assert!(
                out.status.success(),
                "git {args:?}: {}",
                String::from_utf8_lossy(&out.stderr)
            );
        };
        git(&["init", "-q"], &dir);
        std::fs::write(dir.join("a.py"), "x = 1\n").unwrap();
        // The base tracks a .pyc (as checkpoint's `add -A` would after a firing).
        std::fs::create_dir_all(dir.join("__pycache__")).unwrap();
        std::fs::write(dir.join("__pycache__/a.cpython-312.pyc"), b"\x00old").unwrap();
        git(&["add", "-A"], &dir);
        git(
            &[
                "-c",
                "user.email=t@t",
                "-c",
                "user.name=t",
                "commit",
                "-qm",
                "c1",
            ],
            &dir,
        );
        let wt = dir.join("wt");
        git(
            &["worktree", "add", "-q", wt.to_str().unwrap(), "HEAD"],
            &dir,
        );
        // The agent edits a.py and its test run regenerates the tracked .pyc.
        std::fs::write(wt.join("a.py"), "x = 2\n").unwrap();
        std::fs::write(wt.join("__pycache__/a.cpython-312.pyc"), b"\x00new").unwrap();

        let changed = changed_files(&wt, "HEAD");
        assert_eq!(
            changed,
            vec!["a.py"],
            "tracked pyc must not churn: {changed:?}"
        );

        let applied = apply_changes_to(&wt, "HEAD", &dir);
        assert!(
            applied.expect("apply ok"),
            "expected a source change applied"
        );
        assert_eq!(
            std::fs::read_to_string(dir.join("a.py")).unwrap(),
            "x = 2\n"
        );
        // The real tree's cache is untouched — not merged, not deleted.
        assert_eq!(
            std::fs::read(dir.join("__pycache__/a.cpython-312.pyc")).unwrap(),
            b"\x00old",
            "the base's .pyc must be left alone"
        );

        cleanup(&dir, &[wt]);
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// Auto-fix PR mode's git plumbing over a real repo + local bare remote: a
    /// worktree change commits onto a fresh branch (minus pycache) and pushes to
    /// origin. No cwd mutation, no gh, no network.
    #[test]
    fn commit_to_branch_and_push_lands_a_fix_branch() {
        let root = std::env::temp_dir().join(format!("hi-wt-pr-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).unwrap();
        let bare = root.join("remote.git");
        let repo = root.join("repo");
        let git = |args: &[&str], cwd: &Path| {
            let out = Command::new("git")
                .args(args)
                .current_dir(cwd)
                .output()
                .unwrap();
            assert!(
                out.status.success(),
                "git {args:?}: {}",
                String::from_utf8_lossy(&out.stderr)
            );
        };
        git(&["init", "--bare", "-q", bare.to_str().unwrap()], &root);
        git(&["init", "-q", "-b", "main", repo.to_str().unwrap()], &root);
        git(&["config", "user.email", "t@t"], &repo);
        git(&["config", "user.name", "t"], &repo);
        git(&["remote", "add", "origin", bare.to_str().unwrap()], &repo);
        std::fs::write(repo.join("a.py"), "x = 1\n").unwrap();
        git(&["add", "-A"], &repo);
        git(&["commit", "-qm", "c1"], &repo);

        let wt = repo.join("wt");
        git(
            &["worktree", "add", "-q", wt.to_str().unwrap(), "HEAD"],
            &repo,
        );
        // The fix edits a.py and its test run drops bytecode (must not be committed).
        std::fs::write(wt.join("a.py"), "x = 2\n").unwrap();
        std::fs::create_dir_all(wt.join("__pycache__")).unwrap();
        std::fs::write(wt.join("__pycache__/a.cpython-312.pyc"), b"junk").unwrap();

        commit_to_branch(&wt, "hi-autofix/loop1", "hi auto-fix: a").expect("commit ok");
        push_branch(&wt, "hi-autofix/loop1").expect("push ok");

        // The branch landed in the bare remote…
        let show = Command::new("git")
            .current_dir(&bare)
            .args(["rev-parse", "--verify", "hi-autofix/loop1"])
            .output()
            .unwrap();
        assert!(show.status.success(), "branch must exist in the remote");
        // …with the source change but not the pycache.
        let files = Command::new("git")
            .current_dir(&bare)
            .args(["ls-tree", "-r", "--name-only", "hi-autofix/loop1"])
            .output()
            .unwrap();
        let files = String::from_utf8_lossy(&files.stdout);
        assert!(files.contains("a.py"), "a.py committed: {files}");
        assert!(!files.contains(".pyc"), "no pycache in the branch: {files}");

        cleanup(&repo, &[wt]);
        let _ = std::fs::remove_dir_all(&root);
    }

    /// End-to-end reset_to: a worktree with local edits hard-resets onto a new
    /// base commit, discarding its state and adopting the new snapshot.
    #[test]
    fn reset_to_adopts_a_new_base() {
        let dir = std::env::temp_dir().join(format!("hi-wt-reset-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let git = |args: &[&str], cwd: &Path| {
            let out = Command::new("git")
                .args(args)
                .current_dir(cwd)
                .output()
                .unwrap();
            assert!(
                out.status.success(),
                "git {args:?}: {}",
                String::from_utf8_lossy(&out.stderr)
            );
            String::from_utf8_lossy(&out.stdout).trim().to_string()
        };
        git(&["init", "-q"], &dir);
        std::fs::write(dir.join("a.txt"), "one\n").unwrap();
        git(&["add", "-A"], &dir);
        git(
            &[
                "-c",
                "user.email=t@t",
                "-c",
                "user.name=t",
                "commit",
                "-qm",
                "c1",
            ],
            &dir,
        );
        let wt = dir.join("wt");
        git(
            &["worktree", "add", "-q", wt.to_str().unwrap(), "HEAD"],
            &dir,
        );
        // Dirty the worktree, then advance the base in the main repo.
        std::fs::write(wt.join("a.txt"), "dirty\n").unwrap();
        std::fs::write(dir.join("a.txt"), "two\n").unwrap();
        git(&["add", "-A"], &dir);
        git(
            &[
                "-c",
                "user.email=t@t",
                "-c",
                "user.name=t",
                "commit",
                "-qm",
                "c2",
            ],
            &dir,
        );
        let new_base = git(&["rev-parse", "HEAD"], &dir);

        reset_to(&wt, &new_base).expect("reset succeeds");
        assert_eq!(std::fs::read_to_string(wt.join("a.txt")).unwrap(), "two\n");

        cleanup(&dir, &[wt]);
        let _ = std::fs::remove_dir_all(&dir);
    }
}
