[package]
name = "hi-pipefs"
edition.workspace = true
version.workspace = true

[dependencies]
hi-workspace.workspace = true
anyhow.workspace = true
async-trait.workspace = true
blake3.workspace = true
filetime.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tar.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
unicode-normalization.workspace = true
uuid.workspace = true
zstd.workspace = true

[target.'cfg(unix)'.dependencies]
rustix.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
